INSERT INTO cepage (name, taste_level_id)
VALUES
    ('Grenache', NULL),
    ('Petit Verdot', NULL),
    ('Gamay', NULL),
    ('Pinot Noir', NULL),
    ('Sancerre Blanc', NULL),
    ('Chardonnay', NULL),
    ('Picpoul', NULL),
    ('Sémillon', NULL),
    ('Cabernet Sauvignon', NULL),
    ('Syrah', NULL),
    ('Merlot', NULL),
    ('Malbec', NULL),
    ('Carmenère', NULL),
    ('Tannat', NULL),
    ('Petit Syrah', NULL),
    ('Alicante Bouschet', NULL),
    ('Cinsault', NULL),
    ('Dolcetto', NULL),
    ('Zweigelt', NULL),
    ('Blauer Portugieser', NULL),
    ('Nebbiolo', NULL),
    ('Sangiovese', NULL),
    ('Mazuelo', NULL),
    ('Tempranillo', NULL),
    ('Tenlo Blanc', NULL),
    ('Vermentino (Rolle)', NULL),
    ('Grüner Veltliner', NULL),
    ('Albariño', NULL),
    ('Viognier', NULL),
    ('Riesling', NULL),
    ('Chenin Blanc', NULL),
    ('Gewürztraminer', NULL),
    ('Folle Blanche', NULL),
    ('Trebbiano (Ugni Blanc)', NULL),
    ('Melon de Bourgogne', NULL),
    ('Muscon', NULL),
    ('Muscadelle', NULL),
    ('Furmint', NULL),
    ('Palomino', NULL),
    ('Colombard', NULL);
